### PR TITLE
Request Add Candle (CNDL) 

### PR DESCRIPTION
**Pull request by samisbakedham**
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0xbc138bD20C98186CC0342C8e380953aF0cb48BA8
Token Name (from contract): Candle
Token Decimals (from contract): 18
Token Symbol (from contract): CNDL
SushiSwap V2 Pair Address of Token: 

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/commit/de4d77d85ed428632663d2ae6b8a3e31cbe2cefc
Link to the official homepage of token: https://candlelabs.org
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/candle/
Link to official Twitter account: https://twitter.com/candle_labs

### CODE REVIEW

**Comment by matthewlilley** [comment]
@samisbakedham thanks for the request, but would you mind re-opening with this app?

https://partner.sushi.com/

Thanks!

**Comment by samisbakedham** [comment]
Just did thank you

**Comment by samisbakedham** [comment]
> @samisbakedham thanks for the request, but would you mind re-opening with this app?
> 
> https://partner.sushi.com/
> 
> Thanks!

Why didn't you just merge this? C'mon man

**Comment by matthewlilley** [comment]
@samisbakedham if you check the app it was already added

**Comment by samisbakedham** [comment]
> @samisbakedham if you check the app it was already added

I was trying to add it to the actual token list, because Zerion and Rainbow wallet use this list to "verify" tokens as authentic.

**Pull request closed without merging**
